Repository grevend/shamirs-secret-sharing, pull requests merged in 2022-11, with the labels that each got.

#3 Deno port
  .github/workflows/codeql.yml
  .github/workflows/deno.yml
  .github/workflows/linter.yml
  .github/workflows/moscow.yml
  .vscode/settings.json
  deno/.gitignore
  deno/secretsharing.ts
  deno/tests/main.test.ts
  native/secret_sharing.h
Labels: must have

#4 Create release workflow
  .github/workflows/deno.yml
  .github/workflows/release.yml
  deno/secretsharing.ts
Labels: enhancement, must have

#5 Add branch convention usage check
  .github/workflows/branching.yml
Labels: documentation, enhancement, must have

#6 Add README description
  README.md
Labels: documentation, should have
